baseURL: "https://somdeepa.github.io/" 
title: Somdeepa Das
paginate: 30
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Home
          url: 
          weight: 1 
        - name: Research
          url: research/
          weight: 2
        - name: Teaching
          url: teaching/
          weight: 3 
        - name: Resources
          url: resources/
          weight: 4
        - name: Contact
          url: contact/
          weight: 5 


params:
    description: "Hi there! I am a PhD Student in the Economics department of Purdue University. I study how policies and institutions shape economic and social outcomes, using large-scale data and empirical methods. My work examines local regulation, collective bargaining, and the expansion of new markets such as sports betting. Thank you for stopping by!"
    author: Somdeepa Das
    googleAnalyticsID: "G-2M7602VJ63"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    hideSummary: false
    
    profileMode:
          enabled: true
          title: Somdeepa Das
          subtitle: "Hi there! I am a PhD Student in the Economics department of Purdue University. I study how policies and institutions shape economic and social outcomes, using large-scale data and empirical methods. My work examines local regulation, collective bargaining, and the expansion of new markets such as sports betting. Thank you for stopping by!"
          imageUrl: "picture.jpg"
          imageWidth: 200
          imageHeight: 200
          imageTitle: Somdeepa Das
          buttons:
           - name: C.V.
             url: cv/somdeepa_das_cv.pdf
           - name: Research
             url: research/
           - name: Teaching
             url: teaching/
           - name: Contact
             url: contact/

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Somdeepa Das"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
